development:
  user_name: root
  password: roman17
  adapter: mysql2
  database: blogs_db_development
  pool: 5
  timeout: 5000

test:
  user_name: root
  password: roman17
  adapter: mysql2
  database: blogs_db_test
  pool: 5
  timeout: 5000

production:
  user_name: root
  password: roman17
  adapter: mysql2
  database: blogs_db
  pool: 5
  timeout: 5000