development:
  adapter: postgresql
  encoding: unicode
  username: svv
  password: 80502457135
  pool: 5
  host: localhost
  database: blogs_db_develop

test:
  adapter: postgresql
  encoding: unicode
  username: svv
  password: 80502457135
  pool: 5
  host: localhost
  database: blogs_db_test

production:
  adapter: postgresql
  encoding: unicode
  username: svv
  password: 80502457135
  pool: 5
  host: localhost
  database: blogs_db_production